version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: deuze
      POSTGRES_USER: deuze
      POSTGRES_PASSWORD: deuze123
    ports:
      - 5432:5432

  api:
    build: .
    environment:
      DATABASE_URL: postgres://deuze:deuze123@db:5432/deuze
      JWT_SECRET: supersecret
    ports:
      - 3333:3333
    depends_on:
      - db
